---
title: "Untitled"
author: "Ishwara Hegde"
date: "12/3/2020"
output:
  html_document:
    df_print: paged
---

##  Introduction 

The purpose of this introduction is to give a brief recap of the methods that we
will see in the empirical exercise below. Most of the material here 
is taken from Dmitry's new paper,"Synthetic Difference in Differences".
You can check it out (highly recommended) 
[here](https://arxiv.org/pdf/1812.09970.pdf). 

### Setup

* We want to estimate the impact of some policy using panel data. 
* Policy changes not random -- neither across units or time.
* We want to connect connect observed data to unobserved counterfactuals. 

### Solutions

1. DiD : requires parallel trends and large number of units exposed
2. Synthetic control (SC): small no. of units and no parallel trends.

In the paper linked above, Dmitry et. al combine these two methods and call it 
Synthetic Difference-in-Differences:

* Like SC, the method re-weights and matches pre-exposure
trends to weaken the reliance on parallel trend type assumptions.

* Like DID, it is invariant to additive unit-level shifts.

### Mathematical Details 

Recall in DiD we obtain the estimates by solving the following TWFE model:

$$ \tau, \mu, \alpha, \beta =   \sum_i^N \sum_t^T (Y_{it}- \mu -\alpha_i-\beta_t -W_{it} \tau)^2 $$


Notice it introduces two new things:

* With respect to DID, SDID adds the unit and time weights.
* With respect to SC, SDID adds the unit level fixed effects.

>Unit weights are designed so that the average outcome for the treated units 
are approximately parallel to the averages for control units. Time weights are 
designed so that, acknowledging that the difference between treated and control
averages varies over the pre-treatment period, we adjust for the right 
pre-treatment difference: the difference during periods that are predictive of
what happens after treatment.

Unit fixed effects in applications is found to explain much of the variation 
therefore its inclusion reduces bias with respect to standard SC.
